Refactors
Yippy/wish-tally-sheet pull request #2
Opened 2023-07-05 08:00 UTC by bubchi89

2023-07-08 10:34 UTC, FichteFoll commented on src/auto_import.js
> +          var encounteredErrorCode = checkPages(
Ususally, functions report `true` in the success case and not vice versa, but with the variable name it's clean enough.

This is definitely a very valuable refactoring though. Unnecessarily sing globals for error tracking is very spaghetti and prone to errors.

2023-07-09 17:31 UTC, FichteFoll requested changes

2023-07-09 17:31 UTC, FichteFoll commented on src/auto_import.js
> +          if (success) {
This check also needs to be inverted.

2023-07-10 07:34 UTC, FichteFoll approved these changes
I only did a shallow review since I don't know the code base but was somewhat interested in what the "refactoring" was about, but this generally looks good to me. Make of that as you will.

By the way, I can't resolve the discussions I created because I don't have write access to the branch (for obvious reasons).

2023-07-10 10:40 UTC, robqliu commented
Cool, thanks for the review. Yippy said they'd take a look but their hands are full with their work on warp tally. Not super important either way, but figured it might be nice if there are subsequent changes 🤷‍♂️

2023-07-10 10:41 UTC, bubchi89 commented
Cool, thanks for the review. Yippy said they'd take a look but their hands are full with their work on warp tally. Not super important either way, but figured it might be nice if there are subsequent changes 🤷‍♂️

2023-07-10 16:06 UTC, Yippy commented
Overall much better, stripping out the secondary checks that was unnecessary. I will have to move this to Warp Tally later. Also need to add 'AUTO_IMPORT_URL_ERROR_CODE_VISIT_TOO_FREQUENTLY ' that is a new fix in Warp Tally... I will sort that out afterwards.

2024-03-10 17:05 UTC, Yippy approved these changes
Thank you for your PR, there be changes for Genshin Impact v4.5 Chronicled Wish Banners soon.

2024-03-10 17:05 UTC, Yippy commented on .clasp.json
> +    "scriptId": "1HYV03d9Vhm0nrOKz3WgDWOmbCKV0w0cbq3yiXAuuMZerjriqt6rGB108",
Could you remove your google script id from here, with "insert_google_script_id_here"

2024-03-10 17:05 UTC, Yippy commented on src/config.js
> +  range_status(settingsSheet) {
Nice to use classes for setting Import, can the method be renamed to getRangeStatus(settingsSheet), obviously change throughout

2024-03-10 17:05 UTC, Yippy commented on src/config.js
> +  set_range_status(value, settingsSheet) {
Amend setRangeStatus(value, settingsSheet)

2024-03-10 17:05 UTC, Yippy commented on src/config.js
> +  is_toggled(settingsSheet) {
Amend method to isToggled(settingsSheet) or isEnabled()

2024-03-10 17:05 UTC, Yippy commented on src/config.js
> +  range_status(settingsSheet) {
Maybe a better method name, getStatusText()

2024-03-10 17:05 UTC, Yippy commented on src/config.js
> +  set_range_status(value, settingsSheet) {
Maybe a better method name setStatusText()

2024-03-10 17:06 UTC, merged